### ISSUE TITLE
bestlinreg_s -notrans test always returns false

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/EZminc#1]
I was tring to use -notrans and found that it seems to be ignored,

I took at look at the code and this line:
https://github.com/BIC-MNI/EZminc/blob/master/scripts/bestlinreg_s#L234

The last comparison seems to always fail. My guess is because of the comparison of the array and the string, I presume somehow the array needs to be dereferenced but I can't figure out how, my perl fu isn't super-strong.

**Comment by gdevenyi** [comment]
Followup, looks like this works
``@{$conf[$i]{trans}}[0] eq "-est_translations"``

**Comment by vfonov** [comment]
ok, make a pull request then

**Comment by gdevenyi** [comment]
Will do.
