### ISSUE TITLE
itk_resample doesn't properly apply BSplineSyN transforms from antsRegistration

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/EZminc#6]
I was generating some non-linear deformations using antsRegistration.

If I apply them with antsApplyTransforms everything is fine, using itk_resample (and remembering you need to use the inverse transform), the transforms are not applied identically, there is signficant differences.

**Comment by gdevenyi** [comment]
Turns out, after switching to SyN, this is not limited to BSplineSyN, and is not limited to itk_resample, mincresample also applies improperly.

**Comment by vfonov** [comment]
Do you use --minc option?

**Comment by gdevenyi** [comment]
Yes, I'm applying xfm/grid files from antsRegistration packaged in minc-toolkit/1.9.11
