### ISSUE TITLE
Question: how to use lobe_segment.pl?

### ISSUE THREAD

**Issue by oesteban** [BIC-MNI/EZminc#7]
Hi,

I would like to generate the "lobes" segmentation shown here (http://nist.mni.mcgill.ca/?p=904) for the 2009c atlas, in the original MNI space (meaning: the segmentation that matches the template as it is released).

Thanks a lot

**Comment by vfonov** [comment]
crispify mni_icbm152_csf_tal_nlin_sym_09c.mnc 1 mni_icbm152_gm_tal_nlin_sym_09c.mnc 2 mni_icbm152_wm_tal_nlin_sym_09c.mnc 3 -volume mni_icbm152_cls_tal_nlin_sym_09c.mnc
param2xfm identity.xfm identity.xfm 
lobe_segment identity.xfm identity.xfm mni_icbm152_cls_tal_nlin_sym_09c.mnc mni_icbm152_lob_tal_nlin_sym_09c.mnc -template mni_icbm152_t1_tal_nlin_sym_09c.mnc -modeldir mni_icbm152_t1_tal_nlin_sym_09c_atlas
