### ISSUE TITLE
itk_convert flipping brains left-right

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/EZminc#8]
When I convert from mnc to nii.gz:
```
itk_convert $mnimodel test.nii.gz
```
I get:
![image](https://cloud.githubusercontent.com/assets/3001850/20500576/ed35726a-b003-11e6-8dce-3100002c9920.png)

**Comment by vfonov** [comment]
I suggest submitting a bug to https://issues.itk.org

**Comment by gdevenyi** [comment]
https://issues.itk.org/jira/browse/ITK-3503

**Comment by vfonov** [comment]
Well... I thought that was nifti handling issue, but you make it look like MINC handling issue. 
```
itk_convert mni_icbm152_t1_tal_nlin_asym_09c.nrrd test1.nrrd
itk_convert test1.nrrd test2.mnc
```
produces correct result.

**Comment by gdevenyi** [comment]
Yes, the flipping is applied in both directions, but that doesn't fix the problem of when I *start* with what should be co-aligned MINC/NIFTI files, and load them both into an ITK tool (like say antsRegistration) the MINC file is now flipped so registration spectacularly fails.

Take for example this call:
```sh
antsRegistration --dimensionality 3 --float 0 --collapse-output-transforms 1 --verbose --minc \
  --output [$outputdir/$(basename mni_icbm152_t1_tal_nlin_sym_09c.mnc)-$(basename mni_icbm152_t1_tal_nlin_sym_09c.nii)] \
  --winsorize-image-intensities [0.01,0.99] --use-histogram-matching 1 \
  --initial-moving-transform [mni_icbm152_t1_tal_nlin_sym_09c.nii,mni_icbm152_t1_tal_nlin_sym_09c.mnc,1] \
  --transform Rigid[0.1] --metric Mattes[mni_icbm152_t1_tal_nlin_sym_09c.nii,mni_icbm152_t1_tal_nlin_sym_09c.mnc,1,32,Regular,0.25] --convergence [2000x1000x500x250x100x0x0,1e-6,10] --shrink-factors 12x10x8x6x4x2x1 --smoothing-sigmas 10x8x6x4x2x1x0 \
  --transform Similarity[0.1] --metric Mattes[mni_icbm152_t1_tal_nlin_sym_09c.nii,mni_icbm152_t1_tal_nlin_sym_09c.mnc,1,32,Regular,0.25] --convergence [1000x500x250x100x100x0,1e-6,10] --shrink-factors 10x8x6x4x2x1 --smoothing-sigmas 8x6x4x2x1x0 \
  --transform Affine[0.1] --metric Mattes[mni_icbm152_t1_tal_nlin_sym_09c.nii,mni_icbm152_t1_tal_nlin_sym_09c.mnc,1] --convergence [500x250x100x100x100,1e-6,10] --shrink-factors 8x6x4x2x1 --smoothing-sigmas 6x4x2x1x0
```

Both these files are the official releases from the MNI atlases page.

I expect a near-identity transform to result.

Instead:
```sh
> xfm2param mni_icbm152_t1_tal_nlin_sym_09c.mnc-mni_icbm152_t1_tal_nlin_sym_09c.nii0_GenericAffine.xfm
after parameter extraction
-center         0.00000    0.00000    0.00000
-translation   -0.00259  -40.02130  -16.09944
-rotation      42.73930   -0.00053    0.00068
-scale          1.00464    0.97194    1.01209
-shear          0.00000   -0.00001    0.04332
```

Something has gone terribly wrong.

**Comment by vfonov** [comment]
well - don't mix MINC and NIFTI.

**Comment by gdevenyi** [comment]
Thanks to a conversation with @rdvincent we've figured out the issue with the ITK MINC reader:
MINC stores RAS direction cosines while ITK expects LPS direction cosines, so on read and write the direction cosines need to be converted.

I have submitted a patch on the bug here https://issues.itk.org/jira/browse/ITK-3503#comment-27425

**Comment by gdevenyi** [comment]
http://review.source.kitware.com/#/c/21940/
